---
hostPort: localhost:8004
username:
password:

#lowercaseOutputLabelNames: true
#lowercaseOutputName: true
#whitelistObjectNames:
#  - "java.lang:type=GarbageCollector,*"
#  - "java.lang:type=MemoryPool,*"
#  - "java.lang:type=Memory,*"
#  - "java.lang:type=ClassLoading,*"
#  - "java.lang:type=Compilation,*"
#  - "java.lang:type=MemoryManager,*"
#  - "java.lang:type=OperatingSystem,*"
#  - "java.lang:type=Runtime,*"
#  - "java.lang:type=Threading,*"
#  - "org.apache.cassandra.metrics:type=*,scope=*,*"


# ColumnFamily is an alias for Table metrics
#blacklistObjectNames:
#  - "org.apache.cassandra.metrics:type=ColumnFamily,*"
#  - "org.apache.cassandra.metrics:type=Table,keyspace=system_auth,*"
#  - "org.apache.cassandra.metrics:type=Table,keyspace=system,*"
#  - "org.apache.cassandra.metrics:type=Table,keyspace=*,scope=*,name=BloomFilter,*"

rules:
- pattern: "java.lang<type=GarbageCollector, name=(.+)><>(.+):"
  name: java.lang_GC
  type: UNTYPED
  labels:
    "gc_name":     "$1"
    "metric_name": "$2"

- pattern: "java.lang<type=MemoryPool, name=(.+)><(.*)>(.*) "
  name: java_lang_MemoryPool
  type: UNTYPED
  labels:
    "name":   "$1"
    "usage":  "$2"
    "option": "$3"

- pattern: "java.lang<type=Memory><(.*)>(.*):"
  name: java_lang_Memory
  type: UNTYPED
  labels:
    "memory_type":   "$1"
    "metric_name":   "$2"

- pattern: "java.lang<type=ClassLoading><>(.*):"
  name: java_lang_ClassLoading
  type: UNTYPED
  labels:
    "metric_name":   "$1"

- pattern: "java.lang<type=Compilation><>(.*):"
  name: java_lang_Compilation
  type: UNTYPED
  labels:
    "metric_name":   "$1"

- pattern: "java.lang<type=MemoryManager, name=(.*)><>(.*):"
  name: java_lang_MemoryManager
  type: UNTYPED
  labels:
    "metric_name":   "$1"
    "option": "$2"

- pattern: "java.lang<type=OperatingSystem><>(.*):"
  name: java_lang_OperatingSystem
  type: UNTYPED
  labels:
    "metric_name":   "$1"


- pattern: "java.lang<type=Runtime><>(.*):"
  name: java_lang_Runtime
  type: UNTYPED
  labels:
    "metric_name":   "$1"


- pattern: "java.lang<type=Threading><>(.*):"
  name: java_lang_Threading
  type: UNTYPED
  labels:
    "metric_name":   "$1"


- pattern: "JanusGraph Cluster-metrics<name=(.*)><>Count"
  name: "JanusGraph_Count"
  type: UNTYPED
  labels:
    "metric": "$1"

- pattern: "JanusGraph Cluster-metrics<name=(.*)><>Value"
  name: "JanusGraph_Value"
  type: UNTYPED
  labels:
    "metric": "$1"


- pattern: "org.apache.tinkerpop.gremlin.server.GremlinServer.errors><>Count"
  name: "GremlinServer_errors_Count"
  type: UNTYPED
#
- pattern: "org.apache.tinkerpop.gremlin.server.GremlinServer.op.eval><>Count"
  name: "GremlinServer_op.eval_Count"
  type: UNTYPED
